version: 2.1

jobs:
  build-app:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o app.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/stephenpowers601_outlook-com.zip -o lunarCrushData.zip
      - run: sudo apt install -y chromium-browser
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node app 65
  check-app:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o app.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/hassanusman703_outlook-com.zip -o lunarCrushData.zip
      - run: sudo apt install -y chromium-browser
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node app 65
  test-app:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o app.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/johanna.quandt_outlook-com.zip -o lunarCrushData.zip
      - run: sudo apt install -y chromium-browser
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node app 65
  save-data-app:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o app.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/mary.james202_outlook-com.zip -o lunarCrushData.zip
      - run: sudo apt install -y chromium-browser
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node app 65

workflows:
  build:
    jobs:
      - build-app
  check:
    jobs:
      - check-app
  crawl:
    jobs:
      - test-app
  save-data:
    jobs:
      - save-data-app
